/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as SystemAdminControlRouteImport } from './routes/system-admin-control'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyrRouteImport } from './routes/myr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant/index'
import { Route as MyrIndexRouteImport } from './routes/myr/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TenantLoginRouteImport } from './routes/tenant.login'
import { Route as TenantTenantIdRouteImport } from './routes/tenant/$tenantId'
import { Route as MyrSavedRouteImport } from './routes/myr/saved'
import { Route as MyrRoommatesRouteImport } from './routes/myr/roommates'
import { Route as MyrProfileRouteImport } from './routes/myr/profile'
import { Route as MyrOnboardRouteImport } from './routes/myr/onboard'
import { Route as MyrMessagesRouteImport } from './routes/myr/messages'
import { Route as MyrLandlordRouteImport } from './routes/myr/landlord'
import { Route as MyrBrowseRouteImport } from './routes/myr/browse'
import { Route as MyrBookingsRouteImport } from './routes/myr/bookings'
import { Route as LandlordLoginRouteImport } from './routes/landlord.login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminMyrVerificationsRouteImport } from './routes/admin/myr-verifications'
import { Route as AdminFraudRouteImport } from './routes/admin/fraud'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin/diagnostics'
import { Route as AdminAuditsRouteImport } from './routes/admin/audits'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AuthenticatedVerificationsRouteImport } from './routes/_authenticated/verifications'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedRentdeskRouteImport } from './routes/_authenticated/rentdesk'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentVerifyRouteImport } from './routes/_authenticated/payment-verify'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMovesRouteImport } from './routes/_authenticated/moves'
import { Route as AuthenticatedMetersRouteImport } from './routes/_authenticated/meters'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedDepositsRouteImport } from './routes/_authenticated/deposits'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as TenantTenantIdIndexRouteImport } from './routes/tenant/$tenantId.index'
import { Route as MyrLandlordIndexRouteImport } from './routes/myr/landlord/index'
import { Route as TenantTenantIdRoomRouteImport } from './routes/tenant/$tenantId.room'
import { Route as TenantTenantIdRentRouteImport } from './routes/tenant/$tenantId.rent'
import { Route as TenantTenantIdProfileRouteImport } from './routes/tenant/$tenantId.profile'
import { Route as TenantTenantIdNotificationsRouteImport } from './routes/tenant/$tenantId.notifications'
import { Route as TenantTenantIdMeterRouteImport } from './routes/tenant/$tenantId.meter'
import { Route as TenantTenantIdMaintenanceRouteImport } from './routes/tenant/$tenantId.maintenance'
import { Route as TenantTenantIdHistoryRouteImport } from './routes/tenant/$tenantId.history'
import { Route as TenantTenantIdDocumentsRouteImport } from './routes/tenant/$tenantId.documents'
import { Route as TenantTenantIdDepositRouteImport } from './routes/tenant/$tenantId.deposit'
import { Route as MyrRoomIdRouteImport } from './routes/myr/room.$id'
import { Route as MyrListingIdRouteImport } from './routes/myr/listing.$id'
import { Route as MyrLandlordVerifyRouteImport } from './routes/myr/landlord/verify'
import { Route as MyrLandlordNewRouteImport } from './routes/myr/landlord/new'
import { Route as MyrLandlordListingsRouteImport } from './routes/myr/landlord/listings'
import { Route as MyrLandlordInquiriesRouteImport } from './routes/myr/landlord/inquiries'
import { Route as MyrLandlordBookingsRouteImport } from './routes/myr/landlord/bookings'
import { Route as MyrLandlordIdRouteImport } from './routes/myr/landlord/$id'
import { Route as AuthenticatedRoomsRoomIdAnalysisRouteImport } from './routes/_authenticated/rooms_.$roomId.analysis'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminControlRoute = SystemAdminControlRouteImport.update({
  id: '/system-admin-control',
  path: '/system-admin-control',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyrRoute = MyrRouteImport.update({
  id: '/myr',
  path: '/myr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const MyrIndexRoute = MyrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyrRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTenantIdRoute = TenantTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => TenantRoute,
} as any)
const MyrSavedRoute = MyrSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => MyrRoute,
} as any)
const MyrRoommatesRoute = MyrRoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => MyrRoute,
} as any)
const MyrProfileRoute = MyrProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyrRoute,
} as any)
const MyrOnboardRoute = MyrOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => MyrRoute,
} as any)
const MyrMessagesRoute = MyrMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => MyrRoute,
} as any)
const MyrLandlordRoute = MyrLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => MyrRoute,
} as any)
const MyrBrowseRoute = MyrBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => MyrRoute,
} as any)
const MyrBookingsRoute = MyrBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MyrRoute,
} as any)
const LandlordLoginRoute = LandlordLoginRouteImport.update({
  id: '/landlord/login',
  path: '/landlord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyrVerificationsRoute = AdminMyrVerificationsRouteImport.update({
  id: '/myr-verifications',
  path: '/myr-verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditsRoute = AdminAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedVerificationsRoute =
  AuthenticatedVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRentdeskRoute = AuthenticatedRentdeskRouteImport.update({
  id: '/rentdesk',
  path: '/rentdesk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentVerifyRoute =
  AuthenticatedPaymentVerifyRouteImport.update({
    id: '/payment-verify',
    path: '/payment-verify',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovesRoute = AuthenticatedMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetersRoute = AuthenticatedMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepositsRoute = AuthenticatedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TenantTenantIdIndexRoute = TenantTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const MyrLandlordIndexRoute = MyrLandlordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const TenantTenantIdRoomRoute = TenantTenantIdRoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdRentRoute = TenantTenantIdRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdProfileRoute = TenantTenantIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdNotificationsRoute =
  TenantTenantIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => TenantTenantIdRoute,
  } as any)
const TenantTenantIdMeterRoute = TenantTenantIdMeterRouteImport.update({
  id: '/meter',
  path: '/meter',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdMaintenanceRoute =
  TenantTenantIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => TenantTenantIdRoute,
  } as any)
const TenantTenantIdHistoryRoute = TenantTenantIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdDocumentsRoute = TenantTenantIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const TenantTenantIdDepositRoute = TenantTenantIdDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => TenantTenantIdRoute,
} as any)
const MyrRoomIdRoute = MyrRoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => MyrRoute,
} as any)
const MyrListingIdRoute = MyrListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => MyrRoute,
} as any)
const MyrLandlordVerifyRoute = MyrLandlordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const MyrLandlordNewRoute = MyrLandlordNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const MyrLandlordListingsRoute = MyrLandlordListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const MyrLandlordInquiriesRoute = MyrLandlordInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const MyrLandlordBookingsRoute = MyrLandlordBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const MyrLandlordIdRoute = MyrLandlordIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyrLandlordRoute,
} as any)
const AuthenticatedRoomsRoomIdAnalysisRoute =
  AuthenticatedRoomsRoomIdAnalysisRouteImport.update({
    id: '/rooms_/$roomId/analysis',
    path: '/rooms/$roomId/analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/myr': typeof MyrRouteWithChildren
  '/signup': typeof SignupRoute
  '/system-admin-control': typeof SystemAdminControlRoute
  '/tenant': typeof TenantRouteWithChildren
  '/bills': typeof AuthenticatedBillsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/meters': typeof AuthenticatedMetersRoute
  '/moves': typeof AuthenticatedMovesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payment-verify': typeof AuthenticatedPaymentVerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/rentdesk': typeof AuthenticatedRentdeskRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/verifications': typeof AuthenticatedVerificationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/myr-verifications': typeof AdminMyrVerificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/myr/bookings': typeof MyrBookingsRoute
  '/myr/browse': typeof MyrBrowseRoute
  '/myr/landlord': typeof MyrLandlordRouteWithChildren
  '/myr/messages': typeof MyrMessagesRoute
  '/myr/onboard': typeof MyrOnboardRoute
  '/myr/profile': typeof MyrProfileRoute
  '/myr/roommates': typeof MyrRoommatesRoute
  '/myr/saved': typeof MyrSavedRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/tenant/login': typeof TenantLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/myr/': typeof MyrIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/myr/landlord/$id': typeof MyrLandlordIdRoute
  '/myr/landlord/bookings': typeof MyrLandlordBookingsRoute
  '/myr/landlord/inquiries': typeof MyrLandlordInquiriesRoute
  '/myr/landlord/listings': typeof MyrLandlordListingsRoute
  '/myr/landlord/new': typeof MyrLandlordNewRoute
  '/myr/landlord/verify': typeof MyrLandlordVerifyRoute
  '/myr/listing/$id': typeof MyrListingIdRoute
  '/myr/room/$id': typeof MyrRoomIdRoute
  '/tenant/$tenantId/deposit': typeof TenantTenantIdDepositRoute
  '/tenant/$tenantId/documents': typeof TenantTenantIdDocumentsRoute
  '/tenant/$tenantId/history': typeof TenantTenantIdHistoryRoute
  '/tenant/$tenantId/maintenance': typeof TenantTenantIdMaintenanceRoute
  '/tenant/$tenantId/meter': typeof TenantTenantIdMeterRoute
  '/tenant/$tenantId/notifications': typeof TenantTenantIdNotificationsRoute
  '/tenant/$tenantId/profile': typeof TenantTenantIdProfileRoute
  '/tenant/$tenantId/rent': typeof TenantTenantIdRentRoute
  '/tenant/$tenantId/room': typeof TenantTenantIdRoomRoute
  '/myr/landlord/': typeof MyrLandlordIndexRoute
  '/tenant/$tenantId/': typeof TenantTenantIdIndexRoute
  '/rooms/$roomId/analysis': typeof AuthenticatedRoomsRoomIdAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/system-admin-control': typeof SystemAdminControlRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/deposits': typeof AuthenticatedDepositsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/meters': typeof AuthenticatedMetersRoute
  '/moves': typeof AuthenticatedMovesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payment-verify': typeof AuthenticatedPaymentVerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/rentdesk': typeof AuthenticatedRentdeskRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/verifications': typeof AuthenticatedVerificationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/myr-verifications': typeof AdminMyrVerificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/myr/bookings': typeof MyrBookingsRoute
  '/myr/browse': typeof MyrBrowseRoute
  '/myr/messages': typeof MyrMessagesRoute
  '/myr/onboard': typeof MyrOnboardRoute
  '/myr/profile': typeof MyrProfileRoute
  '/myr/roommates': typeof MyrRoommatesRoute
  '/myr/saved': typeof MyrSavedRoute
  '/tenant/login': typeof TenantLoginRoute
  '/admin': typeof AdminIndexRoute
  '/myr': typeof MyrIndexRoute
  '/tenant': typeof TenantIndexRoute
  '/myr/landlord/$id': typeof MyrLandlordIdRoute
  '/myr/landlord/bookings': typeof MyrLandlordBookingsRoute
  '/myr/landlord/inquiries': typeof MyrLandlordInquiriesRoute
  '/myr/landlord/listings': typeof MyrLandlordListingsRoute
  '/myr/landlord/new': typeof MyrLandlordNewRoute
  '/myr/landlord/verify': typeof MyrLandlordVerifyRoute
  '/myr/listing/$id': typeof MyrListingIdRoute
  '/myr/room/$id': typeof MyrRoomIdRoute
  '/tenant/$tenantId/deposit': typeof TenantTenantIdDepositRoute
  '/tenant/$tenantId/documents': typeof TenantTenantIdDocumentsRoute
  '/tenant/$tenantId/history': typeof TenantTenantIdHistoryRoute
  '/tenant/$tenantId/maintenance': typeof TenantTenantIdMaintenanceRoute
  '/tenant/$tenantId/meter': typeof TenantTenantIdMeterRoute
  '/tenant/$tenantId/notifications': typeof TenantTenantIdNotificationsRoute
  '/tenant/$tenantId/profile': typeof TenantTenantIdProfileRoute
  '/tenant/$tenantId/rent': typeof TenantTenantIdRentRoute
  '/tenant/$tenantId/room': typeof TenantTenantIdRoomRoute
  '/myr/landlord': typeof MyrLandlordIndexRoute
  '/tenant/$tenantId': typeof TenantTenantIdIndexRoute
  '/rooms/$roomId/analysis': typeof AuthenticatedRoomsRoomIdAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/myr': typeof MyrRouteWithChildren
  '/signup': typeof SignupRoute
  '/system-admin-control': typeof SystemAdminControlRoute
  '/tenant': typeof TenantRouteWithChildren
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/deposits': typeof AuthenticatedDepositsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/meters': typeof AuthenticatedMetersRoute
  '/_authenticated/moves': typeof AuthenticatedMovesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payment-verify': typeof AuthenticatedPaymentVerifyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/rentdesk': typeof AuthenticatedRentdeskRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/verifications': typeof AuthenticatedVerificationsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audits': typeof AdminAuditsRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/myr-verifications': typeof AdminMyrVerificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/landlord/login': typeof LandlordLoginRoute
  '/myr/bookings': typeof MyrBookingsRoute
  '/myr/browse': typeof MyrBrowseRoute
  '/myr/landlord': typeof MyrLandlordRouteWithChildren
  '/myr/messages': typeof MyrMessagesRoute
  '/myr/onboard': typeof MyrOnboardRoute
  '/myr/profile': typeof MyrProfileRoute
  '/myr/roommates': typeof MyrRoommatesRoute
  '/myr/saved': typeof MyrSavedRoute
  '/tenant/$tenantId': typeof TenantTenantIdRouteWithChildren
  '/tenant/login': typeof TenantLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/myr/': typeof MyrIndexRoute
  '/tenant/': typeof TenantIndexRoute
  '/myr/landlord/$id': typeof MyrLandlordIdRoute
  '/myr/landlord/bookings': typeof MyrLandlordBookingsRoute
  '/myr/landlord/inquiries': typeof MyrLandlordInquiriesRoute
  '/myr/landlord/listings': typeof MyrLandlordListingsRoute
  '/myr/landlord/new': typeof MyrLandlordNewRoute
  '/myr/landlord/verify': typeof MyrLandlordVerifyRoute
  '/myr/listing/$id': typeof MyrListingIdRoute
  '/myr/room/$id': typeof MyrRoomIdRoute
  '/tenant/$tenantId/deposit': typeof TenantTenantIdDepositRoute
  '/tenant/$tenantId/documents': typeof TenantTenantIdDocumentsRoute
  '/tenant/$tenantId/history': typeof TenantTenantIdHistoryRoute
  '/tenant/$tenantId/maintenance': typeof TenantTenantIdMaintenanceRoute
  '/tenant/$tenantId/meter': typeof TenantTenantIdMeterRoute
  '/tenant/$tenantId/notifications': typeof TenantTenantIdNotificationsRoute
  '/tenant/$tenantId/profile': typeof TenantTenantIdProfileRoute
  '/tenant/$tenantId/rent': typeof TenantTenantIdRentRoute
  '/tenant/$tenantId/room': typeof TenantTenantIdRoomRoute
  '/myr/landlord/': typeof MyrLandlordIndexRoute
  '/tenant/$tenantId/': typeof TenantTenantIdIndexRoute
  '/_authenticated/rooms_/$roomId/analysis': typeof AuthenticatedRoomsRoomIdAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/myr'
    | '/signup'
    | '/system-admin-control'
    | '/tenant'
    | '/bills'
    | '/bookings'
    | '/deposits'
    | '/maintenance'
    | '/meters'
    | '/moves'
    | '/notifications'
    | '/onboarding'
    | '/payment-verify'
    | '/profile'
    | '/properties'
    | '/rentdesk'
    | '/rooms'
    | '/settings'
    | '/tenants'
    | '/verifications'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/audits'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/myr-verifications'
    | '/admin/security'
    | '/admin/users'
    | '/landlord/login'
    | '/myr/bookings'
    | '/myr/browse'
    | '/myr/landlord'
    | '/myr/messages'
    | '/myr/onboard'
    | '/myr/profile'
    | '/myr/roommates'
    | '/myr/saved'
    | '/tenant/$tenantId'
    | '/tenant/login'
    | '/admin/'
    | '/myr/'
    | '/tenant/'
    | '/myr/landlord/$id'
    | '/myr/landlord/bookings'
    | '/myr/landlord/inquiries'
    | '/myr/landlord/listings'
    | '/myr/landlord/new'
    | '/myr/landlord/verify'
    | '/myr/listing/$id'
    | '/myr/room/$id'
    | '/tenant/$tenantId/deposit'
    | '/tenant/$tenantId/documents'
    | '/tenant/$tenantId/history'
    | '/tenant/$tenantId/maintenance'
    | '/tenant/$tenantId/meter'
    | '/tenant/$tenantId/notifications'
    | '/tenant/$tenantId/profile'
    | '/tenant/$tenantId/rent'
    | '/tenant/$tenantId/room'
    | '/myr/landlord/'
    | '/tenant/$tenantId/'
    | '/rooms/$roomId/analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/signup'
    | '/system-admin-control'
    | '/bills'
    | '/bookings'
    | '/deposits'
    | '/maintenance'
    | '/meters'
    | '/moves'
    | '/notifications'
    | '/onboarding'
    | '/payment-verify'
    | '/profile'
    | '/properties'
    | '/rentdesk'
    | '/rooms'
    | '/settings'
    | '/tenants'
    | '/verifications'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/audits'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/myr-verifications'
    | '/admin/security'
    | '/admin/users'
    | '/landlord/login'
    | '/myr/bookings'
    | '/myr/browse'
    | '/myr/messages'
    | '/myr/onboard'
    | '/myr/profile'
    | '/myr/roommates'
    | '/myr/saved'
    | '/tenant/login'
    | '/admin'
    | '/myr'
    | '/tenant'
    | '/myr/landlord/$id'
    | '/myr/landlord/bookings'
    | '/myr/landlord/inquiries'
    | '/myr/landlord/listings'
    | '/myr/landlord/new'
    | '/myr/landlord/verify'
    | '/myr/listing/$id'
    | '/myr/room/$id'
    | '/tenant/$tenantId/deposit'
    | '/tenant/$tenantId/documents'
    | '/tenant/$tenantId/history'
    | '/tenant/$tenantId/maintenance'
    | '/tenant/$tenantId/meter'
    | '/tenant/$tenantId/notifications'
    | '/tenant/$tenantId/profile'
    | '/tenant/$tenantId/rent'
    | '/tenant/$tenantId/room'
    | '/myr/landlord'
    | '/tenant/$tenantId'
    | '/rooms/$roomId/analysis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/myr'
    | '/signup'
    | '/system-admin-control'
    | '/tenant'
    | '/_authenticated/bills'
    | '/_authenticated/bookings'
    | '/_authenticated/deposits'
    | '/_authenticated/maintenance'
    | '/_authenticated/meters'
    | '/_authenticated/moves'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/payment-verify'
    | '/_authenticated/profile'
    | '/_authenticated/properties'
    | '/_authenticated/rentdesk'
    | '/_authenticated/rooms'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/_authenticated/verifications'
    | '/admin/activity'
    | '/admin/admins'
    | '/admin/audits'
    | '/admin/diagnostics'
    | '/admin/fraud'
    | '/admin/myr-verifications'
    | '/admin/security'
    | '/admin/users'
    | '/landlord/login'
    | '/myr/bookings'
    | '/myr/browse'
    | '/myr/landlord'
    | '/myr/messages'
    | '/myr/onboard'
    | '/myr/profile'
    | '/myr/roommates'
    | '/myr/saved'
    | '/tenant/$tenantId'
    | '/tenant/login'
    | '/admin/'
    | '/myr/'
    | '/tenant/'
    | '/myr/landlord/$id'
    | '/myr/landlord/bookings'
    | '/myr/landlord/inquiries'
    | '/myr/landlord/listings'
    | '/myr/landlord/new'
    | '/myr/landlord/verify'
    | '/myr/listing/$id'
    | '/myr/room/$id'
    | '/tenant/$tenantId/deposit'
    | '/tenant/$tenantId/documents'
    | '/tenant/$tenantId/history'
    | '/tenant/$tenantId/maintenance'
    | '/tenant/$tenantId/meter'
    | '/tenant/$tenantId/notifications'
    | '/tenant/$tenantId/profile'
    | '/tenant/$tenantId/rent'
    | '/tenant/$tenantId/room'
    | '/myr/landlord/'
    | '/tenant/$tenantId/'
    | '/_authenticated/rooms_/$roomId/analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MyrRoute: typeof MyrRouteWithChildren
  SignupRoute: typeof SignupRoute
  SystemAdminControlRoute: typeof SystemAdminControlRoute
  TenantRoute: typeof TenantRouteWithChildren
  LandlordLoginRoute: typeof LandlordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin-control': {
      id: '/system-admin-control'
      path: '/system-admin-control'
      fullPath: '/system-admin-control'
      preLoaderRoute: typeof SystemAdminControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myr': {
      id: '/myr'
      path: '/myr'
      fullPath: '/myr'
      preLoaderRoute: typeof MyrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/myr/': {
      id: '/myr/'
      path: '/'
      fullPath: '/myr/'
      preLoaderRoute: typeof MyrIndexRouteImport
      parentRoute: typeof MyrRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/login': {
      id: '/tenant/login'
      path: '/login'
      fullPath: '/tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/$tenantId': {
      id: '/tenant/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenant/$tenantId'
      preLoaderRoute: typeof TenantTenantIdRouteImport
      parentRoute: typeof TenantRoute
    }
    '/myr/saved': {
      id: '/myr/saved'
      path: '/saved'
      fullPath: '/myr/saved'
      preLoaderRoute: typeof MyrSavedRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/roommates': {
      id: '/myr/roommates'
      path: '/roommates'
      fullPath: '/myr/roommates'
      preLoaderRoute: typeof MyrRoommatesRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/profile': {
      id: '/myr/profile'
      path: '/profile'
      fullPath: '/myr/profile'
      preLoaderRoute: typeof MyrProfileRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/onboard': {
      id: '/myr/onboard'
      path: '/onboard'
      fullPath: '/myr/onboard'
      preLoaderRoute: typeof MyrOnboardRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/messages': {
      id: '/myr/messages'
      path: '/messages'
      fullPath: '/myr/messages'
      preLoaderRoute: typeof MyrMessagesRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/landlord': {
      id: '/myr/landlord'
      path: '/landlord'
      fullPath: '/myr/landlord'
      preLoaderRoute: typeof MyrLandlordRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/browse': {
      id: '/myr/browse'
      path: '/browse'
      fullPath: '/myr/browse'
      preLoaderRoute: typeof MyrBrowseRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/bookings': {
      id: '/myr/bookings'
      path: '/bookings'
      fullPath: '/myr/bookings'
      preLoaderRoute: typeof MyrBookingsRouteImport
      parentRoute: typeof MyrRoute
    }
    '/landlord/login': {
      id: '/landlord/login'
      path: '/landlord/login'
      fullPath: '/landlord/login'
      preLoaderRoute: typeof LandlordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/myr-verifications': {
      id: '/admin/myr-verifications'
      path: '/myr-verifications'
      fullPath: '/admin/myr-verifications'
      preLoaderRoute: typeof AdminMyrVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audits': {
      id: '/admin/audits'
      path: '/audits'
      fullPath: '/admin/audits'
      preLoaderRoute: typeof AdminAuditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/verifications': {
      id: '/_authenticated/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AuthenticatedVerificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rentdesk': {
      id: '/_authenticated/rentdesk'
      path: '/rentdesk'
      fullPath: '/rentdesk'
      preLoaderRoute: typeof AuthenticatedRentdeskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-verify': {
      id: '/_authenticated/payment-verify'
      path: '/payment-verify'
      fullPath: '/payment-verify'
      preLoaderRoute: typeof AuthenticatedPaymentVerifyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moves': {
      id: '/_authenticated/moves'
      path: '/moves'
      fullPath: '/moves'
      preLoaderRoute: typeof AuthenticatedMovesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meters': {
      id: '/_authenticated/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof AuthenticatedMetersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deposits': {
      id: '/_authenticated/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthenticatedDepositsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tenant/$tenantId/': {
      id: '/tenant/$tenantId/'
      path: '/'
      fullPath: '/tenant/$tenantId/'
      preLoaderRoute: typeof TenantTenantIdIndexRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/myr/landlord/': {
      id: '/myr/landlord/'
      path: '/'
      fullPath: '/myr/landlord/'
      preLoaderRoute: typeof MyrLandlordIndexRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/tenant/$tenantId/room': {
      id: '/tenant/$tenantId/room'
      path: '/room'
      fullPath: '/tenant/$tenantId/room'
      preLoaderRoute: typeof TenantTenantIdRoomRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/rent': {
      id: '/tenant/$tenantId/rent'
      path: '/rent'
      fullPath: '/tenant/$tenantId/rent'
      preLoaderRoute: typeof TenantTenantIdRentRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/profile': {
      id: '/tenant/$tenantId/profile'
      path: '/profile'
      fullPath: '/tenant/$tenantId/profile'
      preLoaderRoute: typeof TenantTenantIdProfileRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/notifications': {
      id: '/tenant/$tenantId/notifications'
      path: '/notifications'
      fullPath: '/tenant/$tenantId/notifications'
      preLoaderRoute: typeof TenantTenantIdNotificationsRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/meter': {
      id: '/tenant/$tenantId/meter'
      path: '/meter'
      fullPath: '/tenant/$tenantId/meter'
      preLoaderRoute: typeof TenantTenantIdMeterRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/maintenance': {
      id: '/tenant/$tenantId/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/$tenantId/maintenance'
      preLoaderRoute: typeof TenantTenantIdMaintenanceRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/history': {
      id: '/tenant/$tenantId/history'
      path: '/history'
      fullPath: '/tenant/$tenantId/history'
      preLoaderRoute: typeof TenantTenantIdHistoryRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/documents': {
      id: '/tenant/$tenantId/documents'
      path: '/documents'
      fullPath: '/tenant/$tenantId/documents'
      preLoaderRoute: typeof TenantTenantIdDocumentsRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/tenant/$tenantId/deposit': {
      id: '/tenant/$tenantId/deposit'
      path: '/deposit'
      fullPath: '/tenant/$tenantId/deposit'
      preLoaderRoute: typeof TenantTenantIdDepositRouteImport
      parentRoute: typeof TenantTenantIdRoute
    }
    '/myr/room/$id': {
      id: '/myr/room/$id'
      path: '/room/$id'
      fullPath: '/myr/room/$id'
      preLoaderRoute: typeof MyrRoomIdRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/listing/$id': {
      id: '/myr/listing/$id'
      path: '/listing/$id'
      fullPath: '/myr/listing/$id'
      preLoaderRoute: typeof MyrListingIdRouteImport
      parentRoute: typeof MyrRoute
    }
    '/myr/landlord/verify': {
      id: '/myr/landlord/verify'
      path: '/verify'
      fullPath: '/myr/landlord/verify'
      preLoaderRoute: typeof MyrLandlordVerifyRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/myr/landlord/new': {
      id: '/myr/landlord/new'
      path: '/new'
      fullPath: '/myr/landlord/new'
      preLoaderRoute: typeof MyrLandlordNewRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/myr/landlord/listings': {
      id: '/myr/landlord/listings'
      path: '/listings'
      fullPath: '/myr/landlord/listings'
      preLoaderRoute: typeof MyrLandlordListingsRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/myr/landlord/inquiries': {
      id: '/myr/landlord/inquiries'
      path: '/inquiries'
      fullPath: '/myr/landlord/inquiries'
      preLoaderRoute: typeof MyrLandlordInquiriesRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/myr/landlord/bookings': {
      id: '/myr/landlord/bookings'
      path: '/bookings'
      fullPath: '/myr/landlord/bookings'
      preLoaderRoute: typeof MyrLandlordBookingsRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/myr/landlord/$id': {
      id: '/myr/landlord/$id'
      path: '/$id'
      fullPath: '/myr/landlord/$id'
      preLoaderRoute: typeof MyrLandlordIdRouteImport
      parentRoute: typeof MyrLandlordRoute
    }
    '/_authenticated/rooms_/$roomId/analysis': {
      id: '/_authenticated/rooms_/$roomId/analysis'
      path: '/rooms/$roomId/analysis'
      fullPath: '/rooms/$roomId/analysis'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedDepositsRoute: typeof AuthenticatedDepositsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMetersRoute: typeof AuthenticatedMetersRoute
  AuthenticatedMovesRoute: typeof AuthenticatedMovesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentVerifyRoute: typeof AuthenticatedPaymentVerifyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedRentdeskRoute: typeof AuthenticatedRentdeskRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedVerificationsRoute: typeof AuthenticatedVerificationsRoute
  AuthenticatedRoomsRoomIdAnalysisRoute: typeof AuthenticatedRoomsRoomIdAnalysisRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedDepositsRoute: AuthenticatedDepositsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMetersRoute: AuthenticatedMetersRoute,
  AuthenticatedMovesRoute: AuthenticatedMovesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentVerifyRoute: AuthenticatedPaymentVerifyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedRentdeskRoute: AuthenticatedRentdeskRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedVerificationsRoute: AuthenticatedVerificationsRoute,
  AuthenticatedRoomsRoomIdAnalysisRoute: AuthenticatedRoomsRoomIdAnalysisRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditsRoute: typeof AdminAuditsRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminMyrVerificationsRoute: typeof AdminMyrVerificationsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditsRoute: AdminAuditsRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminMyrVerificationsRoute: AdminMyrVerificationsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyrLandlordRouteChildren {
  MyrLandlordIdRoute: typeof MyrLandlordIdRoute
  MyrLandlordBookingsRoute: typeof MyrLandlordBookingsRoute
  MyrLandlordInquiriesRoute: typeof MyrLandlordInquiriesRoute
  MyrLandlordListingsRoute: typeof MyrLandlordListingsRoute
  MyrLandlordNewRoute: typeof MyrLandlordNewRoute
  MyrLandlordVerifyRoute: typeof MyrLandlordVerifyRoute
  MyrLandlordIndexRoute: typeof MyrLandlordIndexRoute
}

const MyrLandlordRouteChildren: MyrLandlordRouteChildren = {
  MyrLandlordIdRoute: MyrLandlordIdRoute,
  MyrLandlordBookingsRoute: MyrLandlordBookingsRoute,
  MyrLandlordInquiriesRoute: MyrLandlordInquiriesRoute,
  MyrLandlordListingsRoute: MyrLandlordListingsRoute,
  MyrLandlordNewRoute: MyrLandlordNewRoute,
  MyrLandlordVerifyRoute: MyrLandlordVerifyRoute,
  MyrLandlordIndexRoute: MyrLandlordIndexRoute,
}

const MyrLandlordRouteWithChildren = MyrLandlordRoute._addFileChildren(
  MyrLandlordRouteChildren,
)

interface MyrRouteChildren {
  MyrBookingsRoute: typeof MyrBookingsRoute
  MyrBrowseRoute: typeof MyrBrowseRoute
  MyrLandlordRoute: typeof MyrLandlordRouteWithChildren
  MyrMessagesRoute: typeof MyrMessagesRoute
  MyrOnboardRoute: typeof MyrOnboardRoute
  MyrProfileRoute: typeof MyrProfileRoute
  MyrRoommatesRoute: typeof MyrRoommatesRoute
  MyrSavedRoute: typeof MyrSavedRoute
  MyrIndexRoute: typeof MyrIndexRoute
  MyrListingIdRoute: typeof MyrListingIdRoute
  MyrRoomIdRoute: typeof MyrRoomIdRoute
}

const MyrRouteChildren: MyrRouteChildren = {
  MyrBookingsRoute: MyrBookingsRoute,
  MyrBrowseRoute: MyrBrowseRoute,
  MyrLandlordRoute: MyrLandlordRouteWithChildren,
  MyrMessagesRoute: MyrMessagesRoute,
  MyrOnboardRoute: MyrOnboardRoute,
  MyrProfileRoute: MyrProfileRoute,
  MyrRoommatesRoute: MyrRoommatesRoute,
  MyrSavedRoute: MyrSavedRoute,
  MyrIndexRoute: MyrIndexRoute,
  MyrListingIdRoute: MyrListingIdRoute,
  MyrRoomIdRoute: MyrRoomIdRoute,
}

const MyrRouteWithChildren = MyrRoute._addFileChildren(MyrRouteChildren)

interface TenantTenantIdRouteChildren {
  TenantTenantIdDepositRoute: typeof TenantTenantIdDepositRoute
  TenantTenantIdDocumentsRoute: typeof TenantTenantIdDocumentsRoute
  TenantTenantIdHistoryRoute: typeof TenantTenantIdHistoryRoute
  TenantTenantIdMaintenanceRoute: typeof TenantTenantIdMaintenanceRoute
  TenantTenantIdMeterRoute: typeof TenantTenantIdMeterRoute
  TenantTenantIdNotificationsRoute: typeof TenantTenantIdNotificationsRoute
  TenantTenantIdProfileRoute: typeof TenantTenantIdProfileRoute
  TenantTenantIdRentRoute: typeof TenantTenantIdRentRoute
  TenantTenantIdRoomRoute: typeof TenantTenantIdRoomRoute
  TenantTenantIdIndexRoute: typeof TenantTenantIdIndexRoute
}

const TenantTenantIdRouteChildren: TenantTenantIdRouteChildren = {
  TenantTenantIdDepositRoute: TenantTenantIdDepositRoute,
  TenantTenantIdDocumentsRoute: TenantTenantIdDocumentsRoute,
  TenantTenantIdHistoryRoute: TenantTenantIdHistoryRoute,
  TenantTenantIdMaintenanceRoute: TenantTenantIdMaintenanceRoute,
  TenantTenantIdMeterRoute: TenantTenantIdMeterRoute,
  TenantTenantIdNotificationsRoute: TenantTenantIdNotificationsRoute,
  TenantTenantIdProfileRoute: TenantTenantIdProfileRoute,
  TenantTenantIdRentRoute: TenantTenantIdRentRoute,
  TenantTenantIdRoomRoute: TenantTenantIdRoomRoute,
  TenantTenantIdIndexRoute: TenantTenantIdIndexRoute,
}

const TenantTenantIdRouteWithChildren = TenantTenantIdRoute._addFileChildren(
  TenantTenantIdRouteChildren,
)

interface TenantRouteChildren {
  TenantTenantIdRoute: typeof TenantTenantIdRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantTenantIdRoute: TenantTenantIdRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MyrRoute: MyrRouteWithChildren,
  SignupRoute: SignupRoute,
  SystemAdminControlRoute: SystemAdminControlRoute,
  TenantRoute: TenantRouteWithChildren,
  LandlordLoginRoute: LandlordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
